[meta]
name = "Map Info"
author = "MisfitMaid, XertroV"
category = "Overlay"
version = "0.2.1"
siteid = 320

[script]
dependencies = ["NadeoServices"]
# optional_dependencies = ["BetterLoadingScreen"]
#__DEFINES__
